---
- name: purge old and unofficial docker packages
  apt:
    name: "{{ old_packages }}"
    state: absent
  # Handle errors if the packages fail to purge
  failed_when: false

- name: install docker dependencies
  apt:
    update_cache: yes
    name: "{{ docker_dependencies }}"
    state: present
  # Handle errors if the dependencies fail to install
  failed_when: false

- name: add docker gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  # Handle errors if gpg key fails to add
  failed_when: false

- name: setup docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    state: present
  # Handle errors if repository fails to add
  failed_when: false

- name: install docker
  apt:
    update_cache: yes
    name: "{{ docker_packages }}"
    state: present
  # Handle errors if docker fails to install
  failed_when: false

- name: add user to docker group
  user:
    name: "{{ current_user }}"
    append: yes
    groups: ["docker"]
  # Handle errors if the user already exists in the group
  ignore_errors: true
  failed_when: false
  notify: restart docker service

- name: add user to docker group
  user:
    name: "{{ username }}"
    append: yes
    groups: ["docker"]
  # Handle errors if the user already exists in the group
  ignore_errors: true
  failed_when: false
  notify: restart docker service

- name: setup docker daemon configuration
  copy:
    src: "{{ playbook_dir }}/../docker/"
    dest: /etc/docker/
    owner: "{{ username }}"
    mode: 0644
  # Handle errors if the copy fails
  failed_when: false
  notify:
    - restart docker service
