---
- name: configure sysctl io
  become: true
  sysctl:
    name: "{{ item.token }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: "{{ sysctl_file }}"
    reload: yes
  with_items: "{{ sysctl_io_config }}"
  tags: sysctl

- name: configure sysctl misc
  become: true
  sysctl:
    name: "{{ item.token }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: "{{ sysctl_file }}"
    reload: yes
  with_items: "{{ sysctl_misc_config }}"
  tags: sysctl
